#! /bin/bash -v

set -e

pushd internal-r4jetson
../build-and-push internal-r4jetson
popd
pushd internal-rstudio4jetson
../build-and-push internal-rstudio4jetson &
popd
pushd edgyr-lab
../build-and-push edgyr-lab &
popd
wait
pushd edgyr-studio
../build-and-push edgyr-studio
popd
ps -ef | grep docker
