export EDGYR_HOME=$HOME
export EDGYR_LOGS=$HOME/logs
export EDGYR_PLOTS=$HOME/plots
export EDGYR_SCRIPTS=$HOME/scripts
export LD_LIBRARY_PATH=/usr/local/cuda-10.2/targets/aarch64-linux/lib:$LD_LIBRARY_PATH
export PROJECT_HOME=$HOME/Projects
export WORKON_HOME=$HOME/.virtualenvs

# https://stackoverflow.com/questions/61065541/importerror-usr-lib-aarch64-linux-gnu-libgomp-so-1-cannot-allocate-memory-in
export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1:$LD_PRELOAD

# enable conda
source $HOME/miniconda3/etc/profile.d/conda.sh
