#! /usr/bin/env Rscript

source("~/.Rprofile")
update.packages(ask = FALSE, instlib = Sys.getenv("R_LIBS_USER"), quiet = TRUE)
install.packages(c(
  "caracas",
  "data.table",
  "devtools",
  "IRkernel",
  "keras",
  "knitr",
  "miniUI",
  "opencpu",
  "pkgdown",
  "renv",
  "rmarkdown",
  "rprojroot",
  "rTorch",
  "tidyverse",
  "torch"
), quiet = TRUE)

IRkernel::installspec()
