#! /bin/bash

set -e

apt-get update
apt-get upgrade -y
apt-get install -qqy --no-install-recommends \
  apt-file \
  build-essential \
  ca-certificates \
  fakeroot \
  git \
  git-lfs \
  gnupg \
  mlocate \
  software-properties-common \
  time \
  tree \
  vim-nox

# allow fetching sources and add R Ubuntu repository
cp $SCRIPTS/sources.list.new /etc/apt/sources.list
apt-key adv \
  --keyserver keyserver.ubuntu.com \
  --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
apt-get update

# cleanup
apt-get clean
